# Generated by Django 4.0.3 on 2022-05-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_phone_number_remove_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='born',
            field=models.DateTimeField(null=True),
        ),
    ]
