# Generated by Django 4.0.3 on 2022-05-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='born',
            field=models.DateTimeField(null=True, verbose_name='born date'),
        ),
    ]
