version: "3.9"
   
services:
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=CRM_DJANGO
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=CRM_DJANGO
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db