# Generated by Django 3.1.14 on 2022-05-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_city_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
