# Generated by Django 4.0.3 on 2022-05-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_initial'),
        ('shop', '0002_remove_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.customer'),
            preserve_default=False,
        ),
    ]
