# Generated by Django 4.0.3 on 2022-05-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_adresse_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
