# Generated by Django 4.0.3 on 2022-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_order_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
