# Generated by Django 3.1.14 on 2022-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220421_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
